baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Website Blog | Helen Evangelina"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4

# Site Params
[params]
  dateFormat = "3 SEPTEMBER 2020"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
 
  # Navbar Action Button
  [params.navAction]
    status  = false
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/blog/background.jpg"
    heading               = "Welcome to My Blog! :)"
    tagline               = "Helen Evangelina's Blog"
    primary_button        = "See My Profile"
    primary_button_url    = "about"
    secondary_button      = "My Blog Posts"
    secondary_button_url  = "Blog"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"
    
  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      phone   = "0481777655"
      email   = "heva0001@student.monash.edu"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/helen.evangelina"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/helenevangelinaa"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/helenevangelina/?hl=en"
    